== Solution space

=== About Scriptarnica

In order to simplify the book publishing process and give writers the option to select who they need out of all the middlemen, to enable fast and cheap microtransactions that allow you to pay as you read and only for the content you need, to reward all platform contributors, to build stronger connections between writers and readers, to incentivize the quality of the content and make it the focus, to enable loyalty/karma for all participants and contributors, we are creating the very First Blockchain Based E-Book Platform.

The Platform enables Writers to:

- Make your book available everywhere;
- Lean writing. Publish your work and earn from it immediately, while you write. Get feedback from your readers, engage with them during the writing process;
- No extra costs (i.e., delivery costs) / no exclusive rights limitations;
- Get the highest royalties;
- Simplify the publishing process, without a middleman;
- Get your book analytics.

And it enables Readers to:

- Pay only for the content that you really need;
- Focus on your goals - research driven reading;
- Influence the content while it’s being written, earn from your contribution (as a book reviewer, translator, designer, marketer, or book holder) and read a book before it’s done.
