=== Token Utility

As described in the Problem section, the current book publishing market doesn’t put the quality of the books, writers, and community first. The market is centralized with numerous middlemen in between. That’s why Scriptarnica is designed from the ground up to change the current situation.

A peer-to-peer system will replace the traditional central database with a decentralized one, that will reduce the number of middlemen and make the market more equitable both for readers and writers. The underlying blockchain architecture is capable of processing high volumes of transactions per second, which will enable fast and effective micropayments for all kinds of contributions. Also, Scriptarnica’s pay as you go system will save readers money and time because they will have the opportunity to choose their preferable paragraphs, pages or chapters instead of purchasing the entire book. Thanks to Smart Contracts, the final price for the information will become cheaper and the whole process less time consuming.

In addition, economic incentives enabled by cryptocurrency can dramatically facilitate the growth of a new platform.

In order to build the platform with all these features, Scriptarnica is going to have two tokens: a Script token (SCRPT) and a Character token (CHR).

==== Script Token (SCRPT)

The SCRPT token is the currency of Scriptarnica network and a tradable right to obligate the Scriptarnica network. The main usage of SCRPT is to enable an exchange of e-books for tokens in the cheapest way possible.

Writers uses SCRPT tokens to pay a small fee for publishing books, and after the book is online they can earn SCRPT tokens through the engagement generated by the book. The fee for publishing will go into the pool, which will be used to pay reviewers and other contributors.

Readers use SCRPT to buy books. When a reader buys a book, only a small fee is deducted from this transaction and goes to the platform, whereas the majority goes to the writer.
Reviewers earn SCRPT for reviewing books. For every book approved, honest feedback or any other form of worthwhile contribution, they will be rewarded with SCRPT tokens.

==== Character token (CHR)

In order to get people closer to Scriptarnica and make it easier for everybody to use platform’s services, Scriptarnica will have Character (CHR) tokens in addition to Script tokens.

In spite of the rising popularity of crypto and a decentralized world, a lot of people still find it very hard to understand what it really means, which is the main reason why many very good projects don’t make it off the ground. The main purpose of CHR token and the Burn and Mint Equilibrium method underpinning it is to keep a book’s price intact by the tradable token and enable book lovers that don’t hold cryptocurrency to use the network. Because of this, non-crypto readers will be able to buy a book for fiat (traditional currency).
